SHOW CHARACTER SET;
SELECT * FROM INFORMATION_SCHEMA.CHARACTER_SETS;

SHOW COLLATION WHERE Charset = 'utf8mb4';

-- UCA 9 = Unicode collation algorithm
SELECT COLLATION_NAME, PAD_ATTRIBUTE
FROM INFORMATION_SCHEMA.COLLATIONS
WHERE COLLATION_NAME LIKE 'utf8mb4%';

SELECT
	SCHEMA_NAME as db,
    DEFAULT_CHARACTER_SET_NAME as "CHARSET",
    DEFAULT_COLLATION_NAME as "Collation"
FROM INFORMATION_SCHEMA.SCHEMATA
ORDER BY SCHEMA_NAME;

SELECT
	TABLE_NAME,
	COLUMN_NAME, 
    CHARACTER_SET_NAME, 
    COLLATION_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
AND CHARACTER_SET_NAME IS NOT NULL
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT IF('é' = 'E' COLLATE utf8mb4_0900_ai_ci, "OUI", "NON");
SELECT IF('é' = 'E' COLLATE utf8mb4_0900_as_ci, "OUI", "NON");

SELECT IF('a ' = 'a', "OUI", "NON");
SELECT IF('a ' = 'a' COLLATE utf8mb4_bin, "OUI", "NON");

SET NAMES utf8mb4_0900_as_ci;